# Generated by Django 6.0.3 on 2026-05-24 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('founder', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('date', models.DateField(auto_now_add=True)),
                ('support_requests', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('innovator', '💡 مبتكر'), ('initiative', '🤝 مبادرة'), ('project', '📋 مشروع'), ('university', '🏛️ جامعة')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('added', 'تمت الإضافة')], default='pending', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('full_story', models.TextField(blank=True, null=True)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('news', models.JSONField(blank=True, default=list)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='files/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_item_id', models.IntegerField(blank=True, null=True)),
                ('related_item_title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('attachment_type', models.CharField(default='none', max_length=20)),
                ('attachment_name', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('innovator_name', models.CharField(max_length=150)),
                ('faculty', models.CharField(default='غير محدد', max_length=100)),
                ('category', models.CharField(default='عام', max_length=50)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('team', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('verified', 'موثق')], default='pending', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('interested', models.PositiveIntegerField(default=0)),
                ('ip_status', models.CharField(default='idea', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('support_requests', models.JSONField(blank=True, default=list)),
                ('innovator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'مدير النظام'), ('innovator', 'مبتكر'), ('investor', 'مستثمر')], default='innovator', max_length=20)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('pending', 'قيد الانتظار')], default='active', max_length=20)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('innovator_type', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('investor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('investment_field', models.CharField(blank=True, max_length=100, null=True)),
                ('notifications', models.JSONField(blank=True, default=list)),
                ('support_history', models.JSONField(blank=True, default=list)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
