# Generated by Django 6.0.3 on 2026-05-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='news_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
