# Generated by Django 6.0.3 on 2026-05-24 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_project_news_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='category',
            field=models.CharField(default='عام', max_length=50),
        ),
        migrations.AddField(
            model_name='initiative',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='initiative',
            name='innovator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='initiative',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='initiative',
            name='ip_status',
            field=models.CharField(default='idea', max_length=50),
        ),
        migrations.AddField(
            model_name='initiative',
            name='news_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('verified', 'موثق')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='initiative',
            name='team',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='initiative',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
