# Generated by Django 6.0.3 on 2026-05-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_initiative_category_initiative_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymaker',
            name='category',
            field=models.CharField(default='عام', max_length=50),
        ),
        migrations.AddField(
            model_name='storymaker',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='storymaker',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storymaker',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storymaker',
            name='news_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storymaker',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('verified', 'موثق')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='storymaker',
            name='team',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storymaker',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
