# Generated by Django 6.0.3 on 2026-05-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_storymaker_category_storymaker_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('audio', models.URLField(blank=True, max_length=500, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='podcasts/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
