# Generated by Django 6.0.3 on 2026-05-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
