# Generated by Django 6.0.3 on 2026-05-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_investor_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
