# Generated by Django 6.0.3 on 2026-05-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_service_interested_service_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investor',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
