# Generated by Django 6.0.3 on 2026-05-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_investor_interested_investor_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
